# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the macOS EBBING_HOUSE desktop bundle.

This spec deliberately keeps data-file mapping explicit so the packaged app
preserves the same runtime resource layout expected by `app/core/paths.py`.
"""

from __future__ import annotations

import os
from pathlib import Path

project_root = Path(SPECPATH).resolve().parents[1]
main_script = project_root / "main.py"

# Resource directories bundled read-only into the app.
datas = [
    (str(project_root / "assets" / "images"), "assets/images"),
    (str(project_root / "app" / "assets"), "app/assets"),
    (str(project_root / "app" / "i18n" / "locales"), "app/i18n/locales"),
]

# QtMultimedia is imported conditionally in a few widgets. Explicitly listing
# the module keeps packaging deterministic without over-broad hidden imports.
hiddenimports = ["PySide6.QtMultimedia"]

# The icon is generated by the build script from the canonical PNG branding
# asset. We keep it optional so the build remains usable even if icon tooling
# is unavailable on the current machine.
icon_env = os.environ.get("EBBING_HOUSE_MAC_ICON", "").strip()
icon_path = Path(icon_env) if icon_env else None
mac_icon = str(icon_path) if icon_path and icon_path.exists() else None

a = Analysis(
    [str(main_script)],
    pathex=[str(project_root)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="EBBING_HOUSE",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=mac_icon,
)

app = BUNDLE(
    exe,
    name="EBBING_HOUSE.app",
    icon=mac_icon,
    bundle_identifier="com.ebbinghouse.desktop",
    info_plist={
        "CFBundleDisplayName": "EBBING_HOUSE",
        "CFBundleName": "EBBING_HOUSE",
        "CFBundleShortVersionString": "0.1.0",
        "CFBundleVersion": "0.1.0",
        "LSApplicationCategoryType": "public.app-category.education",
        "NSHighResolutionCapable": True,
        "NSHumanReadableCopyright": "Ebbing House",
    },
)
